### ISSUE TITLE
How to compile with DIY data

### ISSUE THREAD

**Issue by jiayaozhang** [Xrvitd/CWF#1]
Thanks for your great work!

I am trying to use it for some DIY data

But find that it would not compile successfully, if I didn't provide the .xyz files (pointcloud files) in the /CWF/MAIN/main.cpp. 
I am curious do I have to submit xyz files in order to run correctly?

Also the main.cpp in CWF/test folder could not compile successfully for finding `BGAL`
```
find_package(BGAL REQUIRED)
if(BGAL_FOUND)
include_directories(${BGAL_DIR})
endif()
```

**Comment by Xrvitd** [comment]
Hi, thanks for your interest! 
This code must have a .xyz point cloud as input, so if you do not have one, try to sample a point cloud with your target point number. We all use the “Poisson-disk sampling” in meshlab.
And for the compile, which OS are you using? 
Maybe find the closed issues from https://github.com/Xrvitd/RFEPS or https://github.com/Xrvitd/GCNO. They are using the same base code env.

Rui

**Comment by jiayaozhang** [comment]
Thanks for your reply and this wonder project again!
Now it's work and generate nice perfect mesh!

But for production-ready ships which has more than 1,000,000 triangles
* It might take more than 2 hour for a single mesh to process 
* need to preprocess mesh into manifold first before compiling successfully
* some of our ships have self-intersections parts

Hope to see more interesting work in near future!🍭🍟

**Comment by Xrvitd** [comment]
Thank you for your suggestions and interest. 
This code is slower due to the efficiency of RVD, and is also limited by dependent libraries so it requires manifold input. The algorithm can inherently support non-manifold input.
So a GPU-based RVD can be replaced to further improve speed.
