### ISSUE TITLE
Support for Linux Headless Servers

### ISSUE THREAD

**Issue by JYChen18** [Xrvitd/CWF#10]
Hi,

Thank you for your excellent work! 

Are there any plans to support installation on Linux for headless servers?

**Comment by Xrvitd** [comment]
Hi, I never run it on Linux, but you can try to follow this to build on MacOS: https://github.com/Xrvitd/RFEPS/issues/3. They should be similar on Linux.

Rui

**Comment by JYChen18** [comment]
Thanks for your reply! I find it not so difficult and I have already made it. 

Some modifications are listed below if anyone else is interested:
1. Replace `isinf` in `include/BGAL/Optimization/GradientDescent/GradientDescent.h` and `include/BGAL/Optimization/LBFGS/LBFGS.h` with `std::isinf`, which is related to #6 .
2. Replace `gamma` in `src/CVTLike/CVT.cpp` with other names due to the duplicated definition.
3. Replace `<io.h>` in `MAIN/main.cpp` with `<unistd.h>` for Linux/Unix.
4. Replace the path connector `\\` in `src/CVTLike/CVT.cpp` with `/`.
5. Comment out the line 2 in `CMakeLists.txt` and run cmake with the command `cmake .. -DCMAKE_TOOLCHAIN_FILE=${YOUR_PATH_TO_VCPKG_CMAKE} -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++`

**Comment by xyb1314** [comment]
Thanks for your good job! I would like to know that what is the specific installation details for Linux\Ubuntu!
`Please using vcpkg to install dependent libraries!!! (This step I have done it!)
(below essential dependency packages how to install In Liunx OS?)
.\vcpkg install boost:x64-windows
.\vcpkg install cgal:x64-windows
​ use "git pull" if you get errors with the "gmp" library.
.\vcpkg install Eigen3:x64-windows
.\vcpkg install libigl:x64-windows
.\vcpkg integrate install
`
