### ISSUE TITLE
CPD / CVT

### ISSUE THREAD

**Issue by JianlayWang** [Xrvitd/CWF#15]
我在阅读您的代码时发现，代码中在实现RVD的时候对于每个site添加了权重，同时您代码中优化部分有CPD和CVT两种方法，我想问一下，您为什么选择最后基于质心Voronoi图来实现，而不是CPD来实现？CPD有了站点权重后的自由度应该会更高吧？

**Comment by Xrvitd** [comment]
CPD本身的solver不太稳定，而且也很难去给每个点定义一个合理的weight，所以就没有使用。

**Comment by JianlayWang** [comment]
好的，感谢回复。
