### ISSUE TITLE
cwf and MAIN can't run

### ISSUE THREAD

**Issue by mo1shang** [Xrvitd/CWF#17]
Hi,
Thank you for your excellent work.
I was able to run cwf and MAIN at first, and did many times. However, after I deleted the original folder CWF, re-extracted the compressed package and compiled it, it cannot run. Have you ever encountered this situation? Is there a limit to the number of runs?

**Comment by mo1shang** [comment]
![Uploading CWF_run_fail.png…]()

**Comment by mo1shang** [comment]
![CWF_run_fail](https://github.com/user-attachments/assets/7391e1e9-9cac-43b6-a434-aa5ccbbe7352)

**Comment by Xrvitd** [comment]
Hi, we don't have the limit to the number of runs... maybe try changing another input?

**Comment by mo1shang** [comment]
Thanks for your reply, I tried different models, but none of them worked. It's kind of weird. 
I recompiled CWF on another computer, and it works. Thank you again for your work.
