### ISSUE TITLE
疑问: data文件夹中的 n2000_xxx_inputPoints.xyz来源

### ISSUE THREAD

**Issue by KarryCharon** [Xrvitd/CWF#2]
观察到 MAIN程序中 cvt.calculate_ 的调用会依赖于 类似于n2000_bunny_inputPoints.xyz 的点云数据, 请问该部分数据是如何得来的?

**Comment by Xrvitd** [comment]
poisson-disk 采样 作为初始点。



















在 2024-05-17 14:24:19，"KarryCharon" ***@***.***> 写道：

观察到 MAIN程序中 cvt.calculate_ 的调用会依赖于 类似于n2000_bunny_inputPoints.xyz 的点云数据, 请问该部分数据是如何得来的?

**Comment by KarryCharon** [comment]
哦...是不是可以这样理解: 若要集成到自己的功能性软件中, 初始形状的准备需要自己实现对不?
感谢回复!

**Comment by Xrvitd** [comment]
是的 或者你直接接一个采样算法放在这也行。



在 2024-05-17 14:55:48，"KarryCharon" ***@***.***> 写道：

哦...是不是可以这样理解: 若要集成到自己的功能性软件中, 初始形状的准备需要自己实现对不?
感谢回复!

**Comment by KarryCharon** [comment]
> 是的 或者你直接接一个采样算法放在这也行。 在 2024-05-17 14:55:48，"KarryCharon" ***@***.***> 写道： 哦...是不是可以这样理解: 若要集成到自己的功能性软件中, 初始形状的准备需要自己实现对不? 感谢回复! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

好的,理解了! 谢谢
