### ISSUE TITLE
Decimation for textured models

### ISSUE THREAD

**Issue by FishWoWater** [Xrvitd/CWF#3]
Hi, thanks your excellent works!

I am wondering whether CWF can be applied to models with texture mappings and retain the uv parameterization. As far as I know, many feature-preserving decimation algorithms are remesh-based and can't reuse the texture mapping.

Thanks :)

**Comment by Xrvitd** [comment]
Hi! Thanks for your interest, but I am not familiar with texture mapping...

You can find out if there any works using CVT to get textured meshes, if they works, CWF may also works.
















At 2024-05-17 17:24:34, "Junjie Wang" ***@***.***> wrote:

Hi, thanks your excellent works!

I am wondering whether CWF can be applied to models with texture mappings and retain the uv parameterization. As far as I know, many feature-preserving decimation algorithms are remesh-based and can't reuse the texture mapping.

Thanks :)
